apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mpijobs.skatelescope.org
spec:
  group: skatelescope.org
  version: v1
  scope: Namespaced
  names:
    plural: mpijobs
    singular: mpijob
    kind: MPIJob
    shortNames:
    - mj
    - mpij
  additionalPrinterColumns:
  - name: Replicas
    type: integer
    description: The number of Pods in the MPIJob
    JSONPath: .spec.replicas
  validation:
    openAPIV3Schema:
      properties:
        spec:
          title: The MPIJob spec
          description: Either `gpus` or `replicas` should be specified, but not both
          oneOf:
          - properties:
              gpus:
                title: Total number of GPUs
                description: Valid values are 1, 2, 4, or any multiple of 8
                oneOf:
                - type: integer
                  enum:
                  - 1
                  - 2
                  - 4
                - type: integer
                  multipleOf: 8
                  minimum: 8
            required:
            - gpus
          - properties:
              replicas:
                title: Total number of replicas
                description: The GPU resource limit should be specified for each replica
                type: integer
                minimum: 1
            required:
            - replicas

---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: mpi-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: skatelescope.org/v1
    resource: mpijobs
  childResources:
    - apiVersion: v1
      resource: configmaps
    - apiVersion: v1
      resource: serviceaccounts
    - apiVersion: rbac.authorization.k8s.io/v1
      resource: roles
    - apiVersion: rbac.authorization.k8s.io/v1
      resource: rolebindings
    - apiVersion: apps/v1
      resource: statefulsets
    - apiVersion: batch/v1
      resource: jobs
  hooks:
    sync:
      webhook:
        url: http://mpi-controller.metacontroller/sync
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mpi-controller
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpi-controller
  template:
    metadata:
      labels:
        app: mpi-controller
    spec:
      containers:
      - name: controller
        image: python:3-alpine
        command: ["python3", "/hooks/sync.py", "${KUBECTL_IMAGE}"]
        volumeMounts:
        - name: hooks
          mountPath: /hooks
      volumes:
      - name: hooks
        configMap:
          name: mpi-controller
---
apiVersion: v1
kind: Service
metadata:
  name: mpi-controller
  namespace: metacontroller
spec:
  selector:
    app: mpi-controller
  ports:
  - port: 80
